In [1]:
import numpy as np

In [9]:
a = [[1,2,3],[1,2,3],[1,2,3]]

In [10]:
a = np.array(a)

In [11]:
a.ndim

2

In [13]:
a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [12]:
a.size

9

In [15]:
a[0:2,2]

array([3, 3])

In [16]:
import matplotlib.pyplot as plt

In [17]:
#all commands are same as in 1-D. The only difference is you will get an actual array on matrix multiplication.


In [20]:
#for instance
a = np.array([[1,2],[1,3]])
b = np.array([[1,3],[1,2]])
z = a*b
z

array([[1, 6],
       [1, 6]])

In [21]:
z = np.dot(a,b)

In [22]:
z

array([[3, 7],
       [4, 9]])